### ISSUE TITLE
shuffle_batch时提示All shapes must be fully defined

### ISSUE THREAD

**Issue by CSGrandeur** [ycszen/tf_lab#1]
`
ValueError: All shapes must be fully defined: [TensorShape([Dimension(None)]), TensorShape([Dimension(None)])]
`

**Comment by yu-changqian** [comment]
你看你的各种tensor 的shape是否定义好了

**Comment by CSGrandeur** [comment]
多谢回答。好多天过去了我已经忘了问的时候是个什么情况了。。。后来用pipeline搞了。

**Comment by yu-changqian** [comment]
好的。解决了就好。
